#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Jiawen Zhao.
# All rights reserved.

"""
Extract mature miRNA ±1 nt flanking sequences from precursor stem.

Reads a tab-separated file (24 columns, as generated by previous scripts),
locates the mature miRNA sequence within the precursor sequence, and outputs
a FASTA record with a short sequence containing the mature miRNA plus one
additional base on each side (when possible).

The output FASTA header format: ">length=miRNA_ID=Accession"
"""

import sys
import argparse
from typing import Optional


def extract_flanking_sequence(stem: str, target: str) -> Optional[str]:
    """
    Extract target sequence plus one flanking base on each side from stem.

    Args:
        stem: The precursor sequence.
        target: The mature miRNA sequence (or star sequence).

    Returns:
        A substring of stem that includes target and at most one extra base
        on each side. Returns None if target is not found in stem.
    """
    idx = stem.find(target)
    if idx == -1:
        return None
    start = max(0, idx - 1)               # at most one base to the left
    length = len(target) + 2              # target + left + right
    # Ensure we don't exceed the string length
    end = min(start + length, len(stem))
    return stem[start:end]


def process_line(fields, out_handle):
    """
    Process a single line: extract mature sequence, compute flanking region,
    write FASTA record.

    Expected column indices (0-based):
        0: miRNA ID
        1: Accession
        8: Precursor sequence (stem)
        17: Mature sequence
        (21: Star sequence - not used in output)
    """
    if len(fields) < 22:
        print(f"Warning: Line has {len(fields)} columns, skipping.", file=sys.stderr)
        return

    mirna_id = fields[0]
    accession = fields[1]
    stem = fields[8]
    mature = fields[17]

    flank = extract_flanking_sequence(stem, mature)
    if flank is None:
        print(f"Warning: Mature sequence not found in stem for {mirna_id}, skipping.", file=sys.stderr)
        return

    length = len(flank)
    header = f">{length}={mirna_id}={accession}"
    out_handle.write(f"{header}\n{flank}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Extract mature miRNA ±1 nt flanking sequences from precursor stem.",
        epilog="Input file: tab-separated, 24 columns (as from miRNA primary info).\n"
               "Output: FASTA format with header '>length=miRNA_ID=Accession'."
    )
    parser.add_argument('-i', '--input', required=True,
                        help="Input file path (tab-separated, 24 columns).")
    parser.add_argument('-o', '--output', required=True,
                        help="Output FASTA file path.")
    args = parser.parse_args()

    processed = 0
    skipped = 0

    try:
        with open(args.input, 'r') as infh, open(args.output, 'w') as outfh:
            for line_num, line in enumerate(infh, 1):
                line = line.rstrip('\n')
                if not line:
                    continue
                fields = line.split('\t')
                try:
                    process_line(fields, outfh)
                    processed += 1
                except Exception as e:
                    print(f"Warning: Error processing line {line_num}: {e}", file=sys.stderr)
                    skipped += 1
    except Exception as e:
        print(f"Error: Failed to process file {args.input}: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Processing completed.", file=sys.stderr)
    print(f"  Records written: {processed}", file=sys.stderr)
    if skipped:
        print(f"  Records skipped: {skipped}", file=sys.stderr)
    print(f"  Output written to: {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
