#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Jiawen Zhao.
# All rights reserved.

"""
Cluster miRNA loci on the same chromosome and strand within 10 kb intervals.

Reads a tab-separated file with miRNA information (24 columns, as generated by
previous scripts), groups miRNAs by chromosome and strand, sorts by start position,
and merges those with inter‑miRNA distance ≤ 10000 bp into a cluster.

Outputs a cluster summary with cluster ID, species, member list, chromosome,
strand, start and end coordinates.
"""

import sys
import argparse
from typing import Dict, List, Tuple, Optional


def parse_mirna_file(file_path: str) -> Dict[str, List[Tuple[str, str, int, int, str]]]:
    """
    Parse the miRNA basic info file.

    Expected columns (0-based):
        0: miRNA ID (e.g., "N710-MIR156a")
        1: Accession (e.g., "MIR_ID000000001")
        4: Chromosome (e.g., "Chr03")
        5: Strand (+/-)
        6: Start coordinate (int)
        7: End coordinate (int)

    Args:
        file_path: Path to the input file.

    Returns:
        Dictionary keyed by chromosome, each value is a list of tuples:
        (mirna_id, accession, start, end, strand)
    """
    data = {}
    try:
        with open(file_path, 'r') as f:
            for line_num, line in enumerate(f, 1):
                line = line.rstrip('\n')
                if not line:
                    continue
                fields = line.split('\t')
                if len(fields) < 8:
                    print(f"Warning: Line {line_num} has <8 columns, skipping.", file=sys.stderr)
                    continue
                mirna_id = fields[0]
                accession = fields[1]
                chrom = fields[4]
                strand = fields[5]
                try:
                    start = int(fields[6])
                    end = int(fields[7])
                except ValueError as e:
                    print(f"Warning: Line {line_num} invalid start/end: {fields[6]}/{fields[7]}, skipping.", file=sys.stderr)
                    continue
                data.setdefault(chrom, []).append((mirna_id, accession, start, end, strand))
    except Exception as e:
        print(f"Error reading {file_path}: {e}", file=sys.stderr)
        sys.exit(1)
    return data


def cluster_mirnas(data: Dict[str, List[Tuple[str, str, int, int, str]]],
                   distance_threshold: int = 10000) -> List[Dict]:
    """
    Cluster miRNAs per chromosome and strand.

    For each chromosome, sort miRNAs by start coordinate, then cluster consecutive
    miRNAs that are on the same strand and whose gap (end_prev to start_curr) is
    <= distance_threshold.

    Args:
        data: Parsed miRNA data (chromosome -> list of (mirna_id, accession, start, end, strand)).
        distance_threshold: Maximum allowed gap between two miRNA loci to be merged.

    Returns:
        List of cluster dictionaries, each containing:
            - 'chrom': chromosome name
            - 'strand': strand
            - 'beg': start coordinate of the cluster (first miRNA's start)
            - 'end': end coordinate of the cluster (last miRNA's end)
            - 'members': list of "mirna_id=accession" strings (in sorted order)
    """
    clusters = []

    for chrom in sorted(data.keys()):
        entries = data[chrom]
        # Sort by start coordinate
        entries.sort(key=lambda x: x[2])  # x[2] is start

        i = 0
        while i < len(entries):
            # Start a new cluster
            current_members = []
            current_chrom = chrom
            current_strand = entries[i][4]
            current_beg = entries[i][2]
            current_end = entries[i][3]
            current_members.append(f"{entries[i][0]}={entries[i][1]}")
            j = i + 1

            # Extend cluster while conditions hold
            while j < len(entries):
                prev_end = entries[j-1][3]
                curr_start = entries[j][2]
                curr_strand = entries[j][4]
                gap = curr_start - prev_end  # can be negative if overlapping
                if (curr_strand == current_strand and abs(gap) <= distance_threshold):
                    # Merge into cluster
                    current_end = entries[j][3]  # update end to current miRNA's end
                    current_members.append(f"{entries[j][0]}={entries[j][1]}")
                    j += 1
                else:
                    break

            # Store cluster
            clusters.append({
                'chrom': current_chrom,
                'strand': current_strand,
                'beg': current_beg,
                'end': current_end,
                'members': current_members
            })
            i = j  # move to next unprocessed miRNA

    return clusters


def main():
    parser = argparse.ArgumentParser(
        description="Cluster miRNA loci on the same chromosome and strand within 10 kb intervals. "
                    "Only clusters with at least two miRNAs are reported.",
        epilog="Example: %(prog)s -i input.txt -species 'Lactuca sativa' -prefix Lsa -o Lactuca_sativa-cluster.txt",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('-i', '--input', required=True,
                        help="Input file path (miRNA basic info, 24 columns).")
    parser.add_argument('-species', required=True,
                        help="Species name (spaces will be replaced by underscores).")
    parser.add_argument('-prefix', required=True,
                        help="Prefix for cluster IDs (e.g., 'Lsa', 'Ath').")
    parser.add_argument('-o', '--output', required=True,
                        help="Output file path (e.g., ${species}-cluster).")
    parser.add_argument('-d', '--distance', type=int, default=10000,
                        help="Maximum gap between miRNAs to be clustered (default: 10000 bp).")

    args = parser.parse_args()

    # Process species: replace spaces with underscores
    species = args.species.replace(' ', '_')
    prefix = args.prefix

    # Parse input file
    mirna_data = parse_mirna_file(args.input)

    # Perform clustering
    all_clusters = cluster_mirnas(mirna_data, distance_threshold=args.distance)

    # Filter clusters with at least two members
    filtered_clusters = [cl for cl in all_clusters if len(cl['members']) >= 2]

    # Write output
    try:
        with open(args.output, 'w') as out_fh:
            for idx, cl in enumerate(filtered_clusters, start=1):
                cluster_id = f"{prefix}-CL{idx}"
                member_list = ",".join(cl['members'])
                out_fh.write(
                    f"{cluster_id}\t{species}\t{member_list}\t"
                    f"{cl['chrom']}\t{cl['strand']}\t{cl['beg']}\t{cl['end']}\n"
                )
    except Exception as e:
        print(f"Error writing output file {args.output}: {e}", file=sys.stderr)
        sys.exit(1)

    # Summary
    total_input = sum(len(v) for v in mirna_data.values())
    total_clusters = len(all_clusters)
    total_filtered = len(filtered_clusters)
    print(f"Clustering completed.", file=sys.stderr)
    print(f"  Input miRNA loci: {total_input}", file=sys.stderr)
    print(f"  Total clusters (all): {total_clusters}", file=sys.stderr)
    print(f"  Clusters with ≥2 miRNAs: {total_filtered}", file=sys.stderr)
    print(f"  Output written to: {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
